name: run-dmz

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'run-dmz'

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Add CANIUSE_AS_OF_EPOCH to .env
        run: deno scripts/print-as-of-env.ts | tee -a .env

      - name: Build step
        run: 'deno task build'

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'user-agent-info'
          entrypoint: 'main.ts'
          root: '.'
